### ISSUE TITLE
Provide benchmarks

### ISSUE THREAD

**Issue by PragTob** [whitfin/tiny#1]
Hi there,

thanks for creating tiny :) It'd be good imo to share your benchmarks so people can reproduce them and look at them to see what they benchmark etc. - I often just have a `bench` folder in my repos (or well `benchmarks`) :)

Cheers,
Tobi

**Comment by whitfin** [comment]
Hi @PragTob,

I finally got some time for this and added some benchmarks into the `bench/` folder as described. Feel free to PR additions if you feel they need it (I just put some basic ones in there).
